name: Publicar no Facebook

on:
  workflow_dispatch:

jobs:
  post_facebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: |
          python -m pip install requests

      - name: Publicar post no Facebook
        env:
          FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
          FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
        run: |
          python <<EOF
          import requests

          page_id = "${{ secrets.FB_PAGE_ID }}"
          access_token = "${{ secrets.FB_ACCESS_TOKEN }}"
          message = "📢 Novo conteúdo no site Resultados do Jogo! Confira agora em https://resultadosdojogo.com"

          url = f"https://graph.facebook.com/{page_id}/feed"
          payload = {"message": message, "access_token": access_token}
          r = requests.post(url, data=payload)
          print("Status:", r.status_code)
          print("Resposta:", r.text)
          EOF
