name: Publicar no Facebook

on:
  push:
    paths:
      - '**/*.html'

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: pip install requests python-dotenv

      - name: Executar script de postagem
        run: python .github/scripts/post_facebook.py
