name: Publicar no Facebook

on:
  push:
    paths:
      - '**/*.html'     # dispara quando houver commit de arquivos .html
  workflow_dispatch:     # <-- habilita execução manual pelo botão “Run workflow”

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: pip install requests python-dotenv

      - name: Executar script de postagem
        env:
          FB_PAGE_ID:      ${{ secrets.FB_PAGE_ID }}
          FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
        run: python .github/scripts/post_facebook.py
