name: Postar no Facebook

on:
  push:
    paths:
      - '**/*.html'

jobs:
  facebook-post:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar o repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Executar script de postagem no Facebook
      env:
        FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
        FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
      run: python scripts/post_facebook.py
