name: Update Sitemap

on:
  schedule:
    - cron: "0 0 * * *"  # Roda todo dia às 00:00 UTC (21:00 de ontem em -03:00)
  workflow_dispatch:  # Permite execução manual

jobs:
  update-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install xml.etree.ElementTree

      - name: Generate sitemaps
        run: python generate_sitemap.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add sitemapindex.xml sitemaps/*
          git commit -m "Update sitemaps for $(date +%Y-%m-%d)" || echo "No changes to commit"
          git push
